version: '3.2'
services:
  link-service:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    build:
      context: ./postgres/
      dockerfile: Dockerfile
    ports:
    - 5432:5432
    volumes:
    - type: volume
      source: db
      target: /var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "postgres"


volumes:
  db:
